spring:
  application:
    name: jpa
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:iftakhar
    username: iftakhar
    password: anonymous
    driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  port: 8080
